version: "3.7"
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - $HOME/docker/volumes/mongodb:/data/db
    environment:
      - MONGO_INITDB_DATABASE=Thoth
  software_mil:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    